title: kinstone's Blog
description: kinstone's Blog

url: https://kinstone.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10
header: large

navigation:
 - title: Home
   url: /index.html
 - title: Articles (EN)
   url: /articles
 - title: Articles (中文)
   url: /articles-zh
 - title: Categories
   url: /categories
 - title: About
   url: /about


social:
   github: chnhaoran
   email: chnhaoran@gmail.com

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false

google_analytics: "G-LZTRJQTMCY"

# development configurations
host: 0.0.0.0
